// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

const fallbackCiUrl = 'postgresql://ci_user:ci_password@localhost:5432/ci_db';
const databaseUrl = process.env.DATABASE_URL ?? fallbackCiUrl;

export default defineConfig({
	schema: 'prisma/schema.prisma',
	migrations: {
		path: 'prisma/migrations',
		seed: 'tsx prisma/seed.ts',
	},
	datasource: {
		url: databaseUrl,
	},
});
