name: Backend CI

on:
  pull_request: # Trigger the workflow on pull request events for the main and master branches
  push:
    branches: [main]

    # Source - https://stackoverflow.com/a/75939407
# Posted by jessehouwing, modified by community. See post 'Timeline' for change history
# Retrieved 2026-07-29, License - CC BY-SA 4.0

jobs:
  backend-ci:
    name: Build, Lint, Test
    runs-on: ubuntu-latest
    steps:
      - name: Print Text
        run: echo "Hello World!" >> $GITHUB_STEP_SUMMARY
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: npm # Cache npm dependencies to speed up builds

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run ci:check 

      - name: Test
        run: npm test